const path = require("path");
const fs = require("fs");
const SitemapGenerator = require("sitemap-generator");

// サイトマップを生成する対象のURL
const SITE_URL = "https://www.sense-ai.world";

// `public` フォルダが存在しない場合は作成
const publicDir = path.join(__dirname, "public");
if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
}

// サイトマップの保存先
const OUTPUT_PATH = path.join(publicDir, "sitemap.xml");

// 追加する重要なURLリスト
const additionalUrls = [
    "https://www.sense-ai.world/",
    "https://www.sense-ai.world/services",
    "https://www.sense-ai.world/news"
];

// サイトマップのジェネレーターを作成
const generator = SitemapGenerator(SITE_URL, {
    stripQuerystring: true,
    filepath: OUTPUT_PATH
});

// エラー処理
generator.on("error", (error) => {
    console.error("Sitemap generation error:", error);
});

// サイトマップの作成完了後に手動で追加
generator.on("done", () => {
    console.log("✅ Sitemap generated by SitemapGenerator. Adding manual URLs...");

    // 生成されたサイトマップを読み込み
    let sitemapContent = fs.readFileSync(OUTPUT_PATH, "utf8");

    // 追加するURLをXML形式に変換
    const additionalXml = additionalUrls.map(url => `<url><loc>${url}</loc></url>`).join("\n  ");

    // `</urlset>` の直前に追加URLを挿入
    sitemapContent = sitemapContent.replace("</urlset>", `  ${additionalXml}\n</urlset>`);

    // 修正したサイトマップを書き戻す
    fs.writeFileSync(OUTPUT_PATH, sitemapContent, "utf8");

    console.log("✅ Sitemap updated successfully at:", OUTPUT_PATH);
});

// サイトマップの作成開始
generator.start();
