// src/pages/blog/slideai/roi.js
import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import i18nConfig from "../../../../next-i18next.config";
import HomeIcon from "../../homeIcon";
import * as React from "react";

import { FaAppStore, FaCheckCircle, FaRocket, FaClock, FaCalendarAlt, FaChartLine, FaHourglassHalf, FaWallet } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

/* ---------- Constants ---------- */
const LAST_UPDATED_ISO = "2026-02-21";
const APP_STORE_URL = "https://apps.apple.com/jp/app/slideai-pro/id6739415399";

/* ---------- English Fallback Content ---------- */
const EN_FALLBACK = {
  seo: {
    title: "Is Your Time Worth $14.99? The ROI of SlideAI Pro in 2026",
    description: "Stop wasting hours on PowerPoint. Learn how SlideAI Pro saves you 100+ hours a year and why a $14.99 monthly investment pays for itself in just one presentation.",
    ogTitle: "SlideAI Pro ROI: Save 100 Hours a Year for the Price of a Lunch",
    ogDescription: "Calculate your hourly rate vs. manual slide creation. Discover why professionals are switching to SlideAI Pro for maximum efficiency.",
  },
  aria: { home: "SlideAI Home" },
  nav: { blog: "Blog", category: "Efficiency & ROI" },
  hero: {
    h1: "Stop Working Harder, <br>Start Working Smarter",
    tagline: "At $14.99/month, SlideAI Pro isn't an expense—it's a time-generating asset. Turn hours of manual labor into 3 minutes of AI magic.",
    badges: ["Highest ROI", "Time-Saving Tool", "Professional Quality"],
  },
  analysis: {
    h2: "The Math of Efficiency",
    items: [
      { 
        title: "The Old Way", 
        time: "5+ Hours", 
        desc: "Spending precious hours on formatting, alignment, and searching for icons. Labor cost: ~$150+."
      },
      { 
        title: "The SlideAI Way", 
        time: "3 Minutes", 
        desc: "Input your idea, and let AI handle the rest. Cost: $14.99/mo for **unlimited** freedom." 
      }
    ]
  },
  demo: {
    h2: "Visualizing Success: The ROI Deck",
    p1: "Here is a sample of a 'Business Growth & ROI' deck generated by SlideAI Pro in under 180 seconds. Professional aesthetics without the professional price tag.",
    image_captions: [
      "1. Executive Summary & ROI",
      "2. Market Opportunity Analysis",
      "3. Time-to-Market Comparison",
      "4. Operational Efficiency Gains",
      "5. Financial Projections",
      "6. Strategic Roadmap"
    ]
  },
  plans: {
    h2: "The Price of 100 Extra Hours",
    p_desc: "Choose the plan that fits your workflow. The **Monthly Pro** is our most recommended tier for consistent creators who value their freedom.",
    pass7: { name: "7-Day Pass", price: "$9.99", desc: "Perfect for a one-off high-stakes pitch." },
    monthly: { name: "Monthly", price: "$14.99", desc: "The sweet spot for professionals. Unlimited potential." },
    yearly: { name: "Yearly", price: "$149.99", desc: "Maximum savings for long-term power users." },
  },
  cta: {
    h3: "Buy Back Your Time Today.",
    p: "Join thousands of professionals who have reclaimed their weekends. Start your first 2 slides for free.",
    download: "Upgrade to SlideAI Pro"
  }
};

/* ---------- Helpers ---------- */
const getPath = (obj, path) => path.split(".").reduce((o, k) => (o && Object.prototype.hasOwnProperty.call(o, k) ? o[k] : undefined), obj);

function useTx(ns) {
  const { t } = useTranslation(ns);
  const txs = (key) => {
    const val = t(key);
    if (typeof val === "string" && val === key) {
      const fb = getPath(EN_FALLBACK, key);
      return typeof fb === "string" ? fb : key;
    }
    return val;
  };
  const txa = (key) => {
    const val = t(key, { returnObjects: true });
    if (Array.isArray(val) && val.length > 0) return val;
    const fb = getPath(EN_FALLBACK, key);
    return Array.isArray(fb) ? fb : [];
  };
  return { txs, txa };
}

function RenderHtmlText({ text, className }) {
  if (!text) return null;
  return (
    <span className={className}>
      {text.split("<br>").map((line, i) => (
        <React.Fragment key={i}>
          {line}
          {i < text.split("<br>").length - 1 && <br />}
        </React.Fragment>
      ))}
    </span>
  );
}

function SectionCard({ children, className = "", glow = "indigo" }) {
  const glowColor = glow === "fuchsia" ? "bg-fuchsia-500/10" : "bg-emerald-500/10";
  return (
    <section className={"relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.05] p-6 sm:p-8 backdrop-blur shadow-[0_10px_40px_rgba(0,0,0,0.2)] " + className}>
      <div className={`pointer-events-none absolute -top-24 -left-20 h-60 w-60 rounded-full ${glowColor} blur-3xl`} />
      {children}
    </section>
  );
}

function PricingCard({ icon: Icon, name, price, desc, highlight = false }) {
  return (
    <div className={`relative flex flex-col rounded-2xl border p-6 transition-all ${highlight ? "border-emerald-400 bg-emerald-500/10 scale-105 z-10 shadow-xl shadow-emerald-500/20" : "border-white/10 bg-black/30 hover:bg-white/5"}`}>
      <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-white/5 text-emerald-300"><Icon size={24} /></div>
      <h3 className="text-lg font-bold">{name}</h3>
      <div className="mt-2 flex items-baseline gap-1">
        <span className="text-3xl font-bold text-white">{price}</span>
      </div>
      <p className="mt-3 text-sm text-emerald-200/80 leading-relaxed">{desc}</p>
    </div>
  );
}

export default function SlideAIROI() {
  const router = useRouter();
  const { txs, txa } = useTx("blog_slideai_roi");
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.sense-ai.world";
  const canonical = `${siteUrl}/blog/slideai/roi`;

  const demoImages = [
    "/images/slideai/roi-sample-1.jpg",
    "/images/slideai/roi-sample-2.jpg",
    "/images/slideai/roi-sample-3.jpg",
    "/images/slideai/roi-sample-4.jpg",
    "/images/slideai/roi-sample-5.jpg",
    "/images/slideai/roi-sample-6.jpg",
  ];
  const imageCaptions = txa("demo.image_captions");
  const analysisItems = txa("analysis.items");

  return (
    <>
      <Head>
        <title>{txs("seo.title")}</title>
        <meta name="description" content={txs("seo.description")} />
        <link rel="canonical" href={canonical} />
        <meta property="og:title" content={txs("seo.ogTitle")} />
        <meta property="og:description" content={txs("seo.ogDescription")} />
        <meta property="og:image" content={`${siteUrl}/images/slideai/hero.jpg`} />
      </Head>

      <div className={`${inter.className} min-h-screen bg-[#05071c] text-white [background:radial-gradient(1200px_800px_at_10%_-20%,rgba(16,185,129,0.1),transparent),radial-gradient(800px_600px_at_90%_10%,rgba(99,102,241,0.15),transparent)]`}>
        
        <header className="mx-auto max-w-7xl px-6 pt-10 relative z-10">
          <Link href="/home" className="inline-flex items-center justify-center rounded-full border border-white/10 bg-white/5 p-2 text-white/90 backdrop-blur transition hover:bg-white/10">
            <HomeIcon size={28} />
          </Link>
          <nav className="mt-4 text-sm text-indigo-200/80">
            <Link href="/blog" className="hover:underline">{txs("nav.blog")}</Link>
            <span className="mx-2 text-indigo-300/50">/</span>
            <span className="text-indigo-100">{txs("nav.category")}</span>
          </nav>
        </header>

        <main className="mx-auto max-w-4xl px-6 pb-20 pt-10 relative z-10">
          
          <section className="mb-20 text-center">
            <div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-500/10 px-4 py-1.5 text-xs font-medium text-emerald-200 mb-6 mx-auto">
              <FaChartLine size={12} className="text-emerald-400" /> <span>Maximize Your Productivity ROI</span>
            </div>
            <h1 className="bg-gradient-to-r from-white via-emerald-100 to-indigo-100 bg-clip-text text-5xl font-extrabold text-transparent sm:text-7xl leading-tight mb-6">
              <RenderHtmlText text={txs("hero.h1")} />
            </h1>
            <p className="text-xl text-indigo-100/80 leading-relaxed max-w-2xl mx-auto">{txs("hero.tagline")}</p>
            
            <div className="mt-8 flex flex-wrap gap-2 justify-center">
              {txa("hero.badges").map((badge, i) => (
                <span key={i} className="rounded-full bg-white/5 px-4 py-1.5 text-sm text-indigo-100 border border-white/10 backdrop-blur">{badge}</span>
              ))}
            </div>
          </section>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-16">
            {analysisItems.map((item, i) => (
              <div key={i} className={`rounded-2xl border p-8 backdrop-blur ${i === 1 ? "border-emerald-500/30 bg-emerald-500/5 ring-1 ring-emerald-500/20" : "border-white/10 bg-white/5"}`}>
                {i === 0 ? <FaHourglassHalf className="text-red-400 mb-4" size={32} /> : <FaRocket className="text-emerald-400 mb-4" size={32} />}
                <h3 className="text-xl font-bold mb-2">{item.title}</h3>
                <p className={`text-3xl font-bold mb-4 ${i === 1 ? "text-emerald-400" : "text-white"}`}>{item.time}</p>
                <p className={`text-sm leading-relaxed ${i === 1 ? "text-emerald-200/70" : "text-indigo-200/60"}`}>{item.desc}</p>
              </div>
            ))}
          </div>

          <SectionCard className="mb-16" glow="fuchsia">
            <div className="text-center mb-10">
                <h2 className="text-3xl font-bold tracking-tight mb-4">{txs("demo.h2")}</h2>
                <p className="text-indigo-100/90 leading-relaxed text-lg max-w-2xl mx-auto">{txs("demo.p1")}</p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {demoImages.map((src, i) => (
                <div key={i} className="group relative rounded-2xl border border-white/10 bg-black/50 shadow-2xl transition-all hover:border-emerald-500/40 hover:scale-[1.02] overflow-hidden">
                    <div className="aspect-video w-full bg-white/5 relative">
                         {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={src} alt={`SlideAI ROI Sample: ${imageCaptions[i]}`} className="absolute inset-0 h-full w-full object-cover opacity-80 group-hover:opacity-100 transition-opacity" />
                    </div>
                    <div className="p-3 bg-white/5 border-t border-white/5 flex items-center justify-between">
                        <span className="text-xs font-medium text-emerald-200">{imageCaptions[i]}</span>
                        <FaCheckCircle size={14} className="text-emerald-400" />
                    </div>
                </div>
            ))}
            </div>
          </SectionCard>

          <SectionCard className="mb-16 border-emerald-500/20 bg-emerald-500/5" glow="emerald">
            <div className="text-center mb-10">
                <h2 className="text-3xl font-bold">{txs("plans.h2")}</h2>
                <p className="mt-4 text-lg text-indigo-200/80 max-w-2xl mx-auto">{txs("plans.p_desc")}</p>
            </div>
            
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
              <PricingCard icon={FaClock} name={txs("plans.pass7.name")} price={txs("plans.pass7.price")} desc={txs("plans.pass7.desc")} />
              <PricingCard icon={FaWallet} name={txs("plans.monthly.name")} price={txs("plans.monthly.price")} desc={txs("plans.monthly.desc")} highlight={true} />
              <PricingCard icon={FaRocket} name={txs("plans.yearly.name")} price={txs("plans.yearly.price")} desc={txs("plans.yearly.desc")} />
            </div>
          </SectionCard>

          <div className="flex flex-col items-center gap-8 text-center py-10">
            <div className="space-y-3">
              <h3 className="text-4xl font-extrabold text-white">{txs("cta.h3")}</h3>
              <p className="text-xl text-indigo-200/80">{txs("cta.p")}</p>
            </div>
            
            <a href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" className="relative group flex items-center gap-3 rounded-full bg-gradient-to-r from-emerald-600 to-indigo-600 px-10 py-5 text-xl font-bold text-white shadow-[0_0_40px_rgba(16,185,129,0.4)] transition-all hover:scale-105 active:scale-95 hover:shadow-[0_0_60px_rgba(16,185,129,0.6)]">
              <FaAppStore size={32} />
              <span>{txs("cta.download")}</span>
              <div className="absolute inset-0 -z-10 rounded-full bg-white/20 blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
            </a>
            
            <p className="text-[10px] text-indigo-300/40 tracking-widest uppercase font-mono">
              Updated {LAST_UPDATED_ISO} • iOS / iPadOS / macOS (Apple Silicon)
            </p>
          </div>

        </main>
      </div>
    </>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", ["common", "blog_slideai_roi"], i18nConfig)),
    },
  };
}