// src/pages/blog/maildelivery.js

import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import i18nConfig from "../../../next-i18next.config";
import HomeIcon from "../homeIcon";
import { TbWorld } from "react-icons/tb";
import { BsGooglePlay } from "react-icons/bs";
import { FaAppStore } from "react-icons/fa";

// ★ 追加：日付を固定（SEO/ハイドレーションエラー対策）
// 記事のタイトルが "New in 2025" なので、それに合わせた日付に設定
const PUBLISHED_DATE = "2025-12-05T10:00:00+09:00";
const MODIFIED_DATE = "2025-12-08T10:00:00+09:00";

const inter = Inter({ subsets: ["latin"] });

/* ---------- Inline English fallback (Refined & Humanized) ---------- */
const EN_FALLBACK = {
  seo: {
    title:
      "New in 2025: Minutes.AI (iOS) Now Emails Your Minutes Automatically",
    description:
      "Tired of waiting for AI generation? Trusted by 30,000 users, the new Automatic Email Delivery lets you close the app immediately. We'll email the minutes as soon as they're ready.",
    ogTitle:
      "Stop Waiting: Minutes.AI (iOS) Now Emails Minutes Automatically",
    ogDescription:
      "Record, stop, and close the app. We handle the rest. Learn about the new feature that removes the waiting time from your meeting workflow.",
    ld: {
      headline:
        "Minutes.AI for iOS Adds Automatic Email Delivery for Meeting Minutes",
      description:
        "This article explains the new automatic email delivery feature for iOS, allowing users to skip the wait time and have minutes sent directly to their team.",
    },
  },

  aria: { home: "Back to Minutes.AI Home" },

  nav: {
    blog: "Blog",
    maildelivery: "Auto Email Delivery (iOS)",
  },

  hero: {
    kicker: "New iOS Feature 2025",
    h1: "Record, Stop, Done. Your Minutes Are Sent Automatically.",
    // ★ 修正：実績を追加
    tagline:
      "If you've ever searched for an 'AI meeting app' hoping to save time, this update is for you. Join over 30,000 users who have stopped staring at a loading screen waiting for minutes to generate.",
  },

  lead: {
    p1:
      "To our loyal Minutes.AI users: have you ever finished a meeting, hit 'Generate', and then stood there holding your phone, waiting for the text to appear so you could share it? It was a friction point we wanted to fix. With this update, we're removing that wait entirely.",
  },

  feature: {
    h2: "What is 'Automatic Email Delivery'?",
    p1:
      "The concept is simple. You preset your recipients (like your team or manager) in the settings. Then, you simply record your meeting as usual.",
    p2:
      "Previously, you had to keep the app open until the AI finished processing. Now, **you can close the app the second you stop recording.** The backend handles the heavy lifting and automatically emails the finished minutes to your chosen recipients the moment they are ready.",
    note:
      "Note: This feature is currently rolling out for iOS (iPhone/iPad). Android users, stay tuned—we're working on it!",
  },

  benefits: {
    h2: "How This Changes Your Workflow",
    items: [
      {
        t: "1. Sharing becomes 'Unconscious'",
        p:
          "Meeting minutes only have value if they are shared. By automating this step, you ensure that participants and absentees receive the summary instantly, without you ever forgetting to hit 'Send'. It turns a manual chore into an automatic background process.",
      },
      {
        t: "2. Freedom from the 'Quality vs. Speed' Trade-off",
        p:
          "Minutes.AI uses top-tier models like OpenAI Whisper, ChatGPT-5, and Gemini 3. High precision requires processing time—sometimes a few minutes for a long meeting. We know waiting is annoying. With this update, the processing time remains (to ensure quality), but **your waiting time drops to zero**. Put your phone in your pocket and move on to your next task.",
      },
    ],
  },

  who: {
    h2: "Who is the email from?",
    p1:
      "When automatic delivery is on, your team will receive emails from the address below. If you have strict corporate spam filters, please whitelist this domain.",
    address: "no-reply@mg.sense-ai.world",
    bullets: [
      "Sender: no-reply@mg.sense-ai.world",
      "Domain: mg.sense-ai.world (Managed by Minutes.AI / Sense G.K.)",
      "Content: The meeting minutes generated by the app",
    ],
    note:
      "If you see an email from this address, don't worry—it's just the minutes you (or a teammate) recorded.",
  },

  workflow: {
    h2: "Setup in 3 Easy Steps",
    intro:
      "No complicated integrations required. Here is how to get started right now:",
    steps: [
      "1) Go to Settings and add the email addresses you want to send minutes to (e.g., your team alias).",
      "2) Before recording, toggle 'Email Delivery' to ON.",
      "3) Record your meeting and stop when finished.",
      "4) That's it. You can close the app immediately. Our backend (Whisper / GPT-5 / Gemini 3) will process the audio.",
      "5) Once done, the minutes are emailed automatically from no-reply@mg.sense-ai.world.",
      "6) A copy is also saved in your app history for future editing.",
    ],
  },

  unique: {
    h2: "Why We Built This",
    lead:
      "There are plenty of apps that transcribe audio. But our goal isn't just to give you text—it's to help you **finish your work**.",
    bullets: [
      "Most tools stop at 'Here is your text.' You still have to copy, paste, and email it manually.",
      "Minutes.AI focuses on the entire workflow: Recording -> Analysis -> Delivery.",
      "No need for Zapier or complex third-party tools. It's built right into the app.",
      "It's designed for professionals who want the highest accuracy without the wasted time.",
    ],
  },

  faq: {
    h2: "Frequently Asked Questions",
    items: [
      {
        q: "Is automatic delivery mandatory?",
        a:
          "No, it's optional. You can toggle it on or off for each meeting. If you're recording personal notes, just leave it off.",
      },
      {
        q: "Will I get marketing spam?",
        a:
          "Absolutely not. This feature is strictly for delivering your meeting content. We never mix marketing emails with your minutes.",
      },
      {
        q: "Can I change recipients later?",
        a:
          "Yes. You can manage your recipient list in Settings at any time to adapt to different projects or teams.",
      },
      {
        q: "Does this cost extra?",
        a:
          "No. The automatic delivery feature is free. The minutes generated simply consume your existing plan's time (Time Packs or Unlimited Subscription).",
      },
      {
        q: "When is Android coming?",
        a:
          "We are launching on iOS first, but the backend infrastructure is shared. We are working hard to bring this experience to Android soon.",
      },
    ],
  },

  pricing: {
    h2: "Pricing & Plans",
    lead:
      "Worried about hidden costs? Don't be. This feature fits seamlessly into our existing pricing.",
    bullets: [
      "**No Extra Fees:** Auto-delivery is a standard feature for all users.",
      "**Time Packs:** Works perfectly with prepaid minutes (120/1200 mins).",
      "**Unlimited Subscription:** The best value for heavy users. Record all day, auto-send everything, and never worry about limits.",
    ],
    tableNote:
      "Check the app or our pricing page for the latest rates in your region.",
    linkText: "View Full Pricing Details",
  },

  images: {
    main: {
      src: "/images/mainscreen.png",
      alt: "Minutes.AI iPhone main screen showing auto-email settings",
      caption: "Minutes.AI (iOS) — One tap to record, zero wait to share.",
    },
  },

  meta: {
    h2: "Article Info",
    published: "Published",
    type: "Feature Update",
    category: "iOS App",
  },

  cta: {
    openBrowser: "Open Web App",
    downloadIOS: "Download for iOS",
  },
};
/* ---------- end of fallback block ---------- */

/* ---------- tiny helpers ---------- */
const getPath = (obj, path) =>
  path
    .split(".")
    .reduce(
      (o, k) =>
        o && Object.prototype.hasOwnProperty.call(o, k) ? o[k] : undefined,
      obj
    );

const toArray = (v) => {
  if (Array.isArray(v)) return v;
  if (v && typeof v === "object" && !Array.isArray(v)) return Object.values(v);
  return [];
};

/* If i18n returns the key (missing), use EN fallback */
function useTx(ns) {
  const { t } = useTranslation(ns);

  const txs = (key) => {
    const val = t(key);
    if (typeof val === "string" && val === key) {
      const fb = getPath(EN_FALLBACK, key);
      return typeof fb === "string" ? fb : key;
    }
    return val;
  };

  const txa = (key) => {
    const val = t(key, { returnObjects: true });
    if (Array.isArray(val)) return val;
    const fb = getPath(EN_FALLBACK, key);
    return toArray(fb);
  };

  return { txs, txa };
}

/* ---------- UI bits ---------- */
function Kicker({ children }) {
  return (
    <span className="inline-block rounded-full border border-white/15 bg-white/5 px-3 py-1 text-xs tracking-wide text-indigo-100/90">
      {children}
    </span>
  );
}

function SectionCard({ children, className = "" }) {
  return (
    <section
      className={
        "relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.05] p-6 sm:p-8 backdrop-blur " +
        "shadow-[0_10px_40px_rgba(86,77,255,0.12)] " +
        className
      }
    >
      <div className="pointer-events-none absolute -top-24 -left-20 h-60 w-60 rounded-full bg-indigo-500/10 blur-3xl" />
      <div className="pointer-events-none absolute -bottom-24 -right-16 h-56 w-56 rounded-full bg-fuchsia-400/10 blur-3xl" />
      {children}
    </section>
  );
}

function Pill({ children }) {
  return (
    <span className="inline-block rounded-full bg-white/10 px-2.5 py-1 text-xs text-indigo-100/90">
      {children}
    </span>
  );
}

/* ---------- CTA link constants ---------- */
const LINK_HOME = "/home";
const LINK_IOS =
  "https://apps.apple.com/jp/app/%E8%AD%B2%E4%BA%8B%E9%8C%B2ai/id6504087901";
const PLAY_STORE_URL =
  "https://play.google.com/store/apps/details?id=world.senseai.minutes";

export default function BlogMailDelivery() {
  const router = useRouter();
  const { txs, txa } = useTx("blog_maildelivery");

  const siteUrl =
    process.env.NEXT_PUBLIC_SITE_URL || "https://www.sense-ai.world";
  const canonical =
    siteUrl +
    (router.locale === i18nConfig.i18n.defaultLocale
      ? ""
      : `/${router.locale}`) +
    "/blog/maildelivery";

  const benefits = txa("benefits.items");
  const workflowSteps = txa("workflow.steps");
  const uniqueBullets = txa("unique.bullets");
  const faq = txa("faq.items");

  return (
    <>
      <Head>
        {/* ======= SEO ======= */}
        <title>{txs("seo.title")}</title>
        <meta name="description" content={txs("seo.description")} />
        <link rel="canonical" href={canonical} />
        <meta property="og:type" content="article" />
        <meta property="og:title" content={txs("seo.ogTitle")} />
        <meta property="og:description" content={txs("seo.ogDescription")} />
        <meta property="og:url" content={canonical} />
        <meta
          property="og:image"
          content={`${siteUrl}${EN_FALLBACK.images.main.src}`}
        />

        {/* Article structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Article",
              headline: txs("seo.ld.headline"),
              description: txs("seo.ld.description"),
              datePublished: PUBLISHED_DATE,
              dateModified: MODIFIED_DATE,
              mainEntityOfPage: canonical,
              author: { "@type": "Organization", name: "Minutes.AI" },
              publisher: {
                "@type": "Organization",
                name: "Minutes.AI",
                logo: {
                  "@type": "ImageObject",
                  url: `${siteUrl}/icon-master.png`,
                },
              },
              image: [`${siteUrl}${EN_FALLBACK.images.main.src}`],
            }),
          }}
        />

        {/* FAQ structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: faq.map((f) => ({
                "@type": "Question",
                name: f.q,
                acceptedAnswer: { "@type": "Answer", text: f.a },
              })),
            }),
          }}
        />
      </Head>

      <div
        className={`${inter.className} min-h-screen bg-[#0b0e2e] text-white [background:radial-gradient(1200px_800px_at_10%_-20%,rgba(70,69,255,.25),transparent),radial-gradient(800px_600px_at_100%_0%,rgba(192,132,252,.18),transparent)]`}
      >
        {/* Header */}
        <header className="mx-auto max-w-7xl px-6 pt-10 sm:pt-12">
          <Link
            href={LINK_HOME}
            aria-label={txs("aria.home")}
            className="inline-flex items-center justify-center rounded-full border border-white/10 bg-white/5 p-2 text-white/90 backdrop-blur transition hover:bg-white/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-indigo-400/60"
          >
            <HomeIcon size={28} />
          </Link>

          <nav className="mt-4 text-sm text-indigo-200/80">
            <Link href="/blog" className="hover:underline">
              {txs("nav.blog")}
            </Link>
            <span className="mx-2 text-indigo-300/50">/</span>
            <span className="text-indigo-100">
              {txs("nav.maildelivery")}
            </span>
          </nav>
        </header>

        {/* Hero */}
        <section className="relative">
          <div className="mx-auto max-w-3xl px-6 pt-10 pb-6 sm:pt-12 sm:pb-8">
            <Kicker>{txs("hero.kicker")}</Kicker>
            <h1 className="mt-4 text-3xl sm:text-5xl font-extrabold tracking-tight">
              <span className="bg-gradient-to-r from-indigo-200 via-white to-fuchsia-200 bg-clip-text text-transparent drop-shadow">
                {txs("hero.h1")}
              </span>
            </h1>
            <p className="mt-4 text-base leading-7 text-indigo-100/90 max-w-2xl">
              {txs("hero.tagline")}
            </p>
          </div>
        </section>

        {/* Main */}
        <main className="mx-auto max-w-3xl px-6 pb-20">
          {/* Lead */}
          <SectionCard>
            <p className="text-base leading-7 text-indigo-100/90">
              {txs("lead.p1")}
            </p>
          </SectionCard>

          {/* What is the feature */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("feature.h2")}
            </h2>
            <p className="mt-3 text-indigo-100/90">{txs("feature.p1")}</p>
            <p className="mt-3 text-indigo-100/90 font-medium text-white">
              {txs("feature.p2")}
            </p>

            <div className="mt-5 rounded-2xl border border-white/10 bg-black/30 p-3">
              <img
                src={EN_FALLBACK.images.main.src}
                alt={txs("images.main.alt")}
                className="w-full rounded-xl"
                loading="lazy"
              />
              <p className="mt-2 text-xs text-indigo-200/70">
                {txs("images.main.caption")}
              </p>
            </div>

            <p className="mt-4 text-xs text-indigo-200/75">
              {txs("feature.note")}
            </p>
          </SectionCard>

          {/* Benefits */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("benefits.h2")}
            </h2>
            <div className="mt-6 space-y-6">
              {benefits.map((b, i) => (
                <div key={i} className="space-y-2">
                  <h3 className="text-lg font-semibold text-indigo-50">
                    {b.t}
                  </h3>
                  <p className="text-indigo-100/90">{b.p}</p>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Who is this email from */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("who.h2")}
            </h2>
            <p className="mt-3 text-indigo-100/90">{txs("who.p1")}</p>
            <div className="mt-4 rounded-2xl border border-emerald-300/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-50/90">
              <div className="font-mono text-xs uppercase tracking-wide opacity-80">
                Sender
              </div>
              <div className="mt-1 font-semibold break-all">
                {txs("who.address")}
              </div>
            </div>
            <ul className="mt-4 space-y-2 text-sm text-indigo-100/90 list-disc ml-5">
              {txa("who.bullets").map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
            <p className="mt-4 text-xs text-indigo-200/75">{txs("who.note")}</p>
          </SectionCard>

          {/* Workflow */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("workflow.h2")}
            </h2>
            <p className="mt-3 text-indigo-100/90">
              {txs("workflow.intro")}
            </p>
            <ol className="mt-4 space-y-3 text-sm text-indigo-100/90 list-decimal ml-5">
              {workflowSteps.map((step, i) => (
                <li key={i}>{step}</li>
              ))}
            </ol>
          </SectionCard>

          {/* Unique */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("unique.h2")}
            </h2>
            <p className="mt-3 text-indigo-100/90">{txs("unique.lead")}</p>
            <ul className="mt-4 space-y-2 text-sm text-indigo-100/90 list-disc ml-5">
              {uniqueBullets.map((b, i) => (
                <li key={i}>{b}</li>
              ))}
            </ul>
          </SectionCard>

          {/* Pricing section */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("pricing.h2")}
            </h2>
            <p className="mt-3 text-indigo-100/90">
              {txs("pricing.lead")}
            </p>
            <ul className="mt-4 space-y-3 text-indigo-100/90 list-disc ml-5">
              {txa("pricing.bullets").map((b, i) => (
                <li key={i} dangerouslySetInnerHTML={{ __html: b }} />
              ))}
            </ul>
            <p className="mt-3 text-xs text-indigo-200/70">
              {txs("pricing.tableNote")}
            </p>
            <div className="mt-4">
              <Link
                href="/blog/pricing"
                className="rounded-xl bg-white/10 px-4 py-2 text-sm hover:bg-white/20 transition"
              >
                {txs("pricing.linkText")}
              </Link>
            </div>
          </SectionCard>

          {/* FAQ */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("faq.h2")}
            </h2>
            <div className="mt-4 space-y-6">
              {faq.map((f, i) => (
                <div key={i}>
                  <h3 className="text-base font-semibold text-indigo-50">
                    Q. {f.q}
                  </h3>
                  <p className="mt-2 text-indigo-100/90 text-sm leading-relaxed">
                    A. {f.a}
                  </p>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* Meta */}
          <SectionCard className="mt-8">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight">
              {txs("meta.h2")}
            </h2>
            <div className="mt-3 flex flex-wrap gap-2 text-sm text-indigo-100/90">
              <Pill>
                {txs("meta.published")}:{" "}
                {/* ★ 日付を固定化（ハイドレーションエラー回避） */}
                {new Date(PUBLISHED_DATE).toLocaleDateString(router.locale || "en-US", {
                  year: "numeric",
                  month: "short",
                  day: "2-digit",
                })}
              </Pill>
              <Pill>{txs("meta.type")}</Pill>
              <Pill>{txs("meta.category")}</Pill>
            </div>
          </SectionCard>

          {/* CTA */}
          <div className="mt-10 flex flex-wrap gap-4">
            {/* Browser */}
            <Link
              href="/"
              className="group inline-flex items-center gap-2 rounded-full border border-indigo-300/40 bg-indigo-500/10 px-4 py-2.5 text-sm font-medium text-indigo-50/90 backdrop-blur shadow-[0_18px_50px_rgba(79,70,229,0.65)] transition hover:border-indigo-100/80 hover:bg-indigo-500/20 hover:text-white"
            >
              <TbWorld className="text-lg sm:text-xl text-indigo-200 group-hover:text-white" />
              <span>{txs("cta.openBrowser")}</span>
            </Link>

            {/* App Store */}
            <a
              href={LINK_IOS}
              target="_blank"
              rel="noopener noreferrer"
              className="group inline-flex items-center gap-2 rounded-full border border-sky-300/45 bg-sky-500/10 px-4 py-2.5 text-sm font-medium text-sky-50/90 backdrop-blur shadow-[0_18px_50px_rgba(56,189,248,0.65)] transition hover:border-sky-100/80 hover:bg-sky-500/20 hover:text-white"
            >
              <FaAppStore className="text-lg sm:text-xl text-sky-200 group-hover:text-white" />
              <span>{txs("cta.downloadIOS")}</span>
            </a>

            {/* Google Play */}
            <a
              href={PLAY_STORE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="group inline-flex items-center gap-2 rounded-full border border-emerald-300/45 bg-emerald-500/10 px-4 py-2.5 text-sm font-medium text-emerald-50/90 backdrop-blur shadow-[0_18px_50px_rgba(16,185,129,0.7)] transition hover:border-emerald-100/80 hover:bg-emerald-500/20 hover:text-white"
            >
              <BsGooglePlay className="text-lg sm:text-xl text-emerald-200 group-hover:text-white" />
              <span>Google Play</span>
            </a>
          </div>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(
        locale ?? "en",
        ["common", "blog_maildelivery"],
        i18nConfig
      )),
    },
  };
}